import React, { createElement } from 'react'
import { storiesOf } from '@storybook/react'

import Icons from './'

import Wrapper from '../../stories/Wrapper'
import Separator from '../../stories/Separator'

const Icon = ({ type }) => (
  <div
    style={{
      width: 150,
      padding: 5,
      marginBottom: 20,
      alignItems: 'center',
      justifyContent: 'center',
    }}>
    {createElement(Icons[type], {
      style: {
        fontSize: 28,
        alignSelf: 'center',
        marginBottom: 5,
      },
    })}
    <div style={{ textAlign: 'center' }}>{type}</div>
  </div>
)

storiesOf('Core/Icons', module).add('Default', () => (
  <Separator>
    <div style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
      <Icon type="address" />
      <Icon type="adjust" />
      <Icon type="air" />
      <Icon type="alert" />
      <Icon type="archive" />
      <Icon type="arrowCombo" />
      <Icon type="arrowsCcw" />
      <Icon type="attach" />
      <Icon type="attention" />
      <Icon type="back" />
      <Icon type="backInTime" />
      <Icon type="bag" />
      <Icon type="basket" />
      <Icon type="battery" />
      <Icon type="behance" />
      <Icon type="bell" />
      <Icon type="block" />
      <Icon type="book" />
      <Icon type="bookOpen" />
      <Icon type="bookmark" />
      <Icon type="bookmarks" />
      <Icon type="box" />
      <Icon type="briefcase" />
      <Icon type="brush" />
      <Icon type="bucket" />
      <Icon type="calendar" />
      <Icon type="camera" />
      <Icon type="cancel" />
      <Icon type="cancelCircled" />
      <Icon type="cancelSquared" />
      <Icon type="cc" />
      <Icon type="ccBy" />
      <Icon type="ccNc" />
      <Icon type="ccNcEu" />
      <Icon type="ccNcJp" />
      <Icon type="ccNd" />
      <Icon type="ccPd" />
      <Icon type="ccRemix" />
      <Icon type="ccSa" />
      <Icon type="ccShare" />
      <Icon type="ccZero" />
      <Icon type="ccw" />
      <Icon type="cd" />
      <Icon type="chartArea" />
      <Icon type="chartBar" />
      <Icon type="chartLine" />
      <Icon type="chartPie" />
      <Icon type="chat" />
      <Icon type="check" />
      <Icon type="clipboard" />
      <Icon type="clock" />
      <Icon type="cloud" />
      <Icon type="cloudThunder" />
      <Icon type="code" />
      <Icon type="cog" />
      <Icon type="comment" />
      <Icon type="compass" />
      <Icon type="creditCard" />
      <Icon type="cup" />
      <Icon type="cw" />
      <Icon type="database" />
      <Icon type="dbShape" />
      <Icon type="direction" />
      <Icon type="doc" />
      <Icon type="docLandscape" />
      <Icon type="docText" />
      <Icon type="docTextInv" />
      <Icon type="docs" />
      <Icon type="dot" />
      <Icon type="dot2" />
      <Icon type="dot3" />
      <Icon type="down" />
      <Icon type="downBold" />
      <Icon type="downCircled" />
      <Icon type="downDir" />
      <Icon type="downOpen" />
      <Icon type="downOpenBig" />
      <Icon type="downOpenMini" />
      <Icon type="downThin" />
      <Icon type="download" />
      <Icon type="dribbble" />
      <Icon type="dribbbleCircled" />
      <Icon type="drive" />
      <Icon type="dropbox" />
      <Icon type="droplet" />
      <Icon type="erase" />
      <Icon type="evernote" />
      <Icon type="export" />
      <Icon type="eye" />
      <Icon type="facebook" />
      <Icon type="facebookCircled" />
      <Icon type="facebookSquared" />
      <Icon type="fastBackward" />
      <Icon type="fastForward" />
      <Icon type="feather" />
      <Icon type="flag" />
      <Icon type="flash" />
      <Icon type="flashlight" />
      <Icon type="flattr" />
      <Icon type="flickr" />
      <Icon type="flickrCircled" />
      <Icon type="flight" />
      <Icon type="floppy" />
      <Icon type="flowBranch" />
      <Icon type="flowCascade" />
      <Icon type="flowLine" />
      <Icon type="flowParallel" />
      <Icon type="flowTree" />
      <Icon type="folder" />
      <Icon type="forward" />
      <Icon type="gauge" />
      <Icon type="github" />
      <Icon type="githubCircled" />
      <Icon type="globe" />
      <Icon type="googleCircles" />
      <Icon type="gplus" />
      <Icon type="gplusCircled" />
      <Icon type="graduationCap" />
      <Icon type="heart" />
      <Icon type="heartEmpty" />
      <Icon type="help" />
      <Icon type="helpCircled" />
      <Icon type="home" />
      <Icon type="hourglass" />
      <Icon type="inbox" />
      <Icon type="infinity" />
      <Icon type="info" />
      <Icon type="infoCircled" />
      <Icon type="instagrem" />
      <Icon type="install" />
      <Icon type="key" />
      <Icon type="keyboard" />
      <Icon type="lamp" />
      <Icon type="language" />
      <Icon type="lastfm" />
      <Icon type="lastfmCircled" />
      <Icon type="layout" />
      <Icon type="leaf" />
      <Icon type="left" />
      <Icon type="leftBold" />
      <Icon type="leftCircled" />
      <Icon type="leftDir" />
      <Icon type="leftOpen" />
      <Icon type="leftOpenBig" />
      <Icon type="leftOpenMini" />
      <Icon type="leftThin" />
      <Icon type="levelDown" />
      <Icon type="levelUp" />
      <Icon type="lifebuoy" />
      <Icon type="lightDown" />
      <Icon type="lightUp" />
      <Icon type="link" />
      <Icon type="linkedin" />
      <Icon type="linkedinCircled" />
      <Icon type="list" />
      <Icon type="listAdd" />
      <Icon type="location" />
      <Icon type="lock" />
      <Icon type="lockOpen" />
      <Icon type="login" />
      <Icon type="logoDb" />
      <Icon type="logout" />
      <Icon type="loop" />
      <Icon type="magnet" />
      <Icon type="mail" />
      <Icon type="map" />
      <Icon type="megaphone" />
      <Icon type="menu" />
      <Icon type="mic" />
      <Icon type="minus" />
      <Icon type="minusCircled" />
      <Icon type="minusSquared" />
      <Icon type="mixi" />
      <Icon type="mobile" />
      <Icon type="monitor" />
      <Icon type="moon" />
      <Icon type="mouse" />
      <Icon type="music" />
      <Icon type="mute" />
      <Icon type="network" />
      <Icon type="newspaper" />
      <Icon type="note" />
      <Icon type="noteBeamed" />
      <Icon type="palette" />
      <Icon type="paperPlane" />
      <Icon type="pause" />
      <Icon type="paypal" />
      <Icon type="pencil" />
      <Icon type="phone" />
      <Icon type="picasa" />
      <Icon type="picture" />
      <Icon type="pinterest" />
      <Icon type="pinterestCircled" />
      <Icon type="play" />
      <Icon type="plus" />
      <Icon type="plusCircled" />
      <Icon type="plusSquared" />
      <Icon type="popup" />
      <Icon type="print" />
      <Icon type="progress0" />
      <Icon type="progress1" />
      <Icon type="progress2" />
      <Icon type="progress3" />
      <Icon type="publish" />
      <Icon type="qq" />
      <Icon type="quote" />
      <Icon type="rdio" />
      <Icon type="rdioCircled" />
      <Icon type="record" />
      <Icon type="renren" />
      <Icon type="reply" />
      <Icon type="replyAll" />
      <Icon type="resizeFull" />
      <Icon type="resizeSmall" />
      <Icon type="retweet" />
      <Icon type="right" />
      <Icon type="rightBold" />
      <Icon type="rightCircled" />
      <Icon type="rightDir" />
      <Icon type="rightOpen" />
      <Icon type="rightOpenBig" />
      <Icon type="rightOpenMini" />
      <Icon type="rightThin" />
      <Icon type="rocket" />
      <Icon type="rss" />
      <Icon type="search" />
      <Icon type="share" />
      <Icon type="shareable" />
      <Icon type="shuffle" />
      <Icon type="signal" />
      <Icon type="sinaWeibo" />
      <Icon type="skype" />
      <Icon type="skypeCircled" />
      <Icon type="smashing" />
      <Icon type="sound" />
      <Icon type="soundcloud" />
      <Icon type="spotify" />
      <Icon type="spotifyCircled" />
      <Icon type="star" />
      <Icon type="starEmpty" />
      <Icon type="stop" />
      <Icon type="stumbleupon" />
      <Icon type="stumbleuponCircled" />
      <Icon type="suitcase" />
      <Icon type="sweden" />
      <Icon type="switch" />
      <Icon type="tag" />
      <Icon type="tape" />
      <Icon type="target" />
      <Icon type="thermometer" />
      <Icon type="thumbsDown" />
      <Icon type="thumbsUp" />
      <Icon type="ticket" />
      <Icon type="toEnd" />
      <Icon type="toStart" />
      <Icon type="tools" />
      <Icon type="trafficCone" />
      <Icon type="trash" />
      <Icon type="trophy" />
      <Icon type="tumblr" />
      <Icon type="tumblrCircled" />
      <Icon type="twitter" />
      <Icon type="twitterCircled" />
      <Icon type="up" />
      <Icon type="upBold" />
      <Icon type="upCircled" />
      <Icon type="upDir" />
      <Icon type="upOpen" />
      <Icon type="upOpenBig" />
      <Icon type="upOpenMini" />
      <Icon type="upThin" />
      <Icon type="upload" />
      <Icon type="uploadCloud" />
      <Icon type="user" />
      <Icon type="userAdd" />
      <Icon type="users" />
      <Icon type="vcard" />
      <Icon type="video" />
      <Icon type="vimeo" />
      <Icon type="vimeoCircled" />
      <Icon type="vkontakte" />
      <Icon type="volume" />
      <Icon type="water" />
      <Icon type="window" />
    </div>
  </Separator>
))
